resources/views/auth/register.blade.php
resources/views/proponente/cadastro.blade.php

Melhorias no cadastro de proponente.

Cadastro de proponente ao criar projeto

---

app/Http/Controllers/Auth/RegisterController.php
app/Http/Controllers/ProponenteController.php
app/Providers/AppServiceProvider.php
app/Utils/LattesValidation.php
config/mail.php
resources/views/auth/register.blade.php
resources/views/layouts/app.blade.php
resources/views/proponente/cadastro.blade.php
resources/views/vendor/notifications/email.blade.php

Cadastro:
* UFAPE como opção de instituição
* validação do link para Lattes
* validação para nível de pesquisa
* CPF único para usuário
Email:
* Alterando remetente padrão do email

Alterações no cadastro e email

---

app/Http/Controllers/TrabalhoController.php

Ao editar um projeto, não era possível adicionar participantes que já são cadastrados no sistema.
Foi adicionada uma verificação na função update de Trabalho.

Fix add participante

---

app/Http/Controllers/AdministradorController.php
resources/views/evento/visualizarEvento.blade.php
resources/views/layouts/app.blade.php

Correções texto descrição, email rodapé

---

app/Http/Middleware/checkCoordenador.php
resources/views/coordenadorComissao/editais.blade.php
resources/views/proponente/index.blade.php
routes/web.php

Mensagem de email e correções de coordenador

---

app/Http/Kernel.php
app/Http/Middleware/checkRoles.php
resources/views/componentes/participante.blade.php
resources/views/evento/formulario/anexos.blade.php
resources/views/evento/formulario/participantes.blade.php
resources/views/evento/submeterTrabalho.blade.php
resources/views/projeto/editar.blade.php
resources/views/projeto/formulario/anexos.blade.php
resources/views/projeto/formulario/participantes.blade.php
resources/views/projeto/visualizar.blade.php
resources/views/proponente/projetos.blade.php
resources/views/proponente/projetosEdital.blade.php
routes/web.php

Correções em submeter proposta

---

app/Http/Controllers/AvaliadorController.php
resources/views/avaliador/listarTrabalhos.blade.php
resources/views/avaliador/parecerInterno.blade.php

Restrição do envio de parecer para avaliador interno;
adição de coluna para status em avaliador

Restrição do envio de parecer | adição de coluna para status

---

app/Http/Controllers/TrabalhoController.php
app/Trabalho.php
database/migrations/2022_11_08_214901_add_conflitos_interesse_to_trabalhos_table.php
resources/views/administrador/analisarProposta.blade.php
resources/views/evento/formulario/proponente.blade.php
resources/views/projeto/editaFormulario/proponente.blade.php
resources/views/projeto/formularioVisualizar/proponente.blade.php
resources/views/projeto/formularioVisualizar/proponente2.blade.php

Esse commit visa adicionar o campo "Conflitos de Interesse" para a entidade Trabalho.
Através desse campo, os proponentes poderão informar, por exemplo, se possuem algum conflito com algum professor e não gostaria que ele avaliasse seu trabalho.
Algumas informações:
- No banco de dados, é uma coluna do tipo "text";
- No front, é representado por um "textarea";
- É diferente para cada projeto;
- Não é obrigatório.

Adicionando conflitos de interesse

---

app/Http/Controllers/AdministradorController.php
app/Http/Controllers/Auth/RegisterController.php
app/Http/Controllers/CursoController.php
app/Http/Controllers/ObjetivoDeDesenvolvimentoSustentavelController.php
app/Http/Controllers/TrabalhoController.php
app/Http/Controllers/UserController.php
database/migrations/2023_02_14_165401_add_curso_id_to_participantes.php
database/seeds/CursoSeeder.php
database/seeds/DatabaseSeeder.php
resources/views/administrador/analisarProposta.blade.php
resources/views/administrador/index.blade.php
resources/views/auth/register.blade.php
resources/views/cursos/create.blade.php
resources/views/cursos/edit.blade.php
resources/views/cursos/index.blade.php
resources/views/naturezas/grandeArea/index.blade.php
resources/views/projeto/formularioVisualizar/relatorio.blade.php
resources/views/projeto/visualizar.blade.php
resources/views/proponente/projetos.blade.php
resources/views/user/perfilUser.blade.php
routes/web.php

- Seleção de áreas temáticas no perfiel do avaliador
- Verificação na exclusão de uma ODS
- Permitir que admin crie novos cursos
- Alteração no texto do status do projeto

Modificações realizadas no sistema durante a sprint 

---

resources/views/evento/formulario/integrantes.blade.php
resources/views/projeto/formularioVisualizar/integrantes.blade.php
resources/views/proponente/projetos.blade.php
routes/web.php

Quando adicionar um integrante no perfil de proponente o botão de adicionar está centralizado.
Agora os integrantes também terão um campo para visualizar as informações assim como os discentes.

Issue #738 concluída. E Issue #746 concluída.

---

app/Http/Controllers/Auth/RegisterController.php
app/Http/Controllers/TrabalhoController.php
resources/views/evento/formulario/integrantes.blade.php
resources/views/evento/formulario/projeto.blade.php

Corrige texto repetido e motra curso do participante no modal do integrante na tela de submeter projeto

---

app/Http/Controllers/AreaTematicaController.php
resources/views/evento/formulario/integrantes.blade.php
resources/views/evento/formulario/projeto.blade.php
resources/views/projeto/editaFormulario/projeto.blade.php

carrega macara do cpf quando a página é carregada

---

resources/views/evento/formulario/projeto.blade.php
resources/views/evento/submeterTrabalho.blade.php

Mostra função do participante ao adicionar no projeto

---

resources/views/evento/formulario/finalizar.blade.php
resources/views/evento/submeterTrabalho.blade.php

coloca campo do rascunho como 1o input

---

app/Http/Controllers/TrabalhoController.php
app/Participante.php
resources/views/projeto/editaFormulario/integrantes.blade.php
resources/views/projeto/editaFormulario/participantes.blade.php

Salva função do participante no banco e mostra na edição do rascunho/projeto

---

resources/views/evento/formulario/participantes.blade.php

inputs do participante como leitura e recupera valor

---

app/Http/Controllers/TrabalhoController.php
resources/views/proponente/projetos.blade.php
resources/views/proponente/projetosEdital.blade.php

Edicao somente de rascunho

---

app/Http/Requests/StoreTrabalho.php

checa se o mesmo integrante foi add mais de uma vez

---

app/Http/Controllers/UserController.php
app/User.php
resources/views/user/perfilParticipante.blade.php

Tela para o participante atualizar os dados

---

resources/views/evento/formulario/participantes.blade.php
resources/views/evento/submeterTrabalho.blade.php

Corrige função do participante quando ocorre erro na submissão

---

resources/views/evento/formulario/integrantes.blade.php
resources/views/evento/formulario/participantes.blade.php
resources/views/evento/submeterTrabalho.blade.php
resources/views/projeto/editaFormulario/integrantes.blade.php
resources/views/projeto/editar.blade.php

Permite adicionar mais participantes se ocorrer erro na submissão

---

app/Http/Requests/StoreTrabalho.php

This reverts commit ee45b2753d0a92eb66d4636621b0050a6191d254.

Revert "log da razão do request falhar"

---

resources/views/evento/submeterTrabalho.blade.php

Ajustadas [informações do integrante](https://github.com/lmtsufape/submeta/issues/798) ao ser inserido na submissão de proposta de projeto

Ajustadas informações do integrante

---

resources/views/administrador/substituirParticipante.blade.php

Quando se realizava a substituição de um discente que não completo o perfil de Participante no sistema nenhum erro ou aviso era informado ao usuário

Modal de erro ao discente não possuir perfil completo

---

resources/views/administrador/substituirParticipante.blade.php

Assim que a correção estiver ok as duas opções voltarão ao sistema

Remoção temporaria das duas opções de substituição que não funcionam

---

app/Http/Requests/StoreTrabalho.php
resources/views/evento/formulario/anexos.blade.php

remocao da flag do questionario de pesquisa de prospeccao interna no pibic e pibiti
